server:
  port: 8082

spring:
  application:
    name: patient-service
  
  # Database Configuration - For Docker (MySQL in container)
  datasource:
    url: jdbc:mysql://mysql-patient:3306/patient_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Shaini8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      file-size-threshold: 2KB

# Eureka client
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

# Cloudinary Configuration
cloudinary:
  cloud-name: dwona3xzj
  api-key: 541144828641826
  api-secret: RoOFJQi-nLfT0_ExZewiJ_TsOak

# File Storage Configuration
app:
  storage:
    type: cloudinary
  file:
    upload-dir: ./uploads/patients
  base-url: http://localhost:8082

# Logging
logging:
  level:
    com.healthcare.patient: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"